# Generated by Django 3.2.4 on 2021-06-17 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='mapel',
        ),
        migrations.CreateModel(
            name='Mengajar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.mapel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.teacher')),
            ],
        ),
    ]
