# Generated by Django 3.2.4 on 2021-06-18 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_auto_20210617_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.mapel')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.teacher')),
            ],
        ),
    ]
