# Generated by Django 3.2.4 on 2021-06-19 00:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0005_auto_20210619_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesiswa',
            name='uploaded_at',
            field=models.DateField(default=datetime.datetime(2021, 6, 19, 0, 10, 3, 901543, tzinfo=utc)),
        ),
    ]
