# Generated by Django 3.2.4 on 2021-06-19 00:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0006_alter_filesiswa_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='materi',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2021, 6, 19, 0, 30, 43, 717589, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filesiswa',
            name='uploaded_at',
            field=models.DateField(default=datetime.datetime(2021, 6, 19, 0, 30, 39, 159573, tzinfo=utc)),
        ),
    ]
