# Generated by Django 3.2.4 on 2021-06-19 00:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0007_auto_20210619_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesiswa',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 0, 33, 43, 555783, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='materi',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
