# Generated by Django 3.2.4 on 2021-06-19 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0008_auto_20210619_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesiswa',
            name='nilai',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filesiswa',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 8, 50, 23, 380339)),
        ),
    ]
