# Generated by Django 3.2.4 on 2021-06-19 19:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0009_auto_20210619_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesiswa',
            name='nilai',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='filesiswa',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 19, 21, 55, 538615)),
        ),
    ]
