# Generated by Django 3.2.4 on 2021-06-21 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0010_auto_20210619_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesiswa',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 11, 58, 2, 342970)),
        ),
    ]
