# Generated by Django 3.2.4 on 2021-06-21 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0011_alter_filesiswa_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesiswa',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 12, 41, 53, 128392)),
        ),
        migrations.AlterField(
            model_name='materi',
            name='slug',
            field=models.SlugField(),
        ),
    ]
