# Generated by Django 3.2.4 on 2021-06-22 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0012_auto_20210621_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesiswa',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 16, 10, 6, 410173)),
        ),
    ]
