# Generated by Django 3.2.4 on 2021-06-22 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0013_alter_filesiswa_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesiswa',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 16, 16, 37, 928731)),
        ),
    ]
