# Generated by Django 3.2.4 on 2021-06-25 13:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0014_alter_filesiswa_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesiswa',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 13, 30, 11, 422994)),
        ),
        migrations.CreateModel(
            name='ArchiveMateri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progresshash', models.CharField(max_length=200)),
                ('materi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_management.materi')),
            ],
        ),
    ]
