# Generated by Django 3.2.4 on 2021-06-25 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0015_auto_20210625_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesiswa',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 25, 14, 25, 45, 329863)),
        ),
    ]
