# Generated by Django 3.2.4 on 2021-06-26 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0011_auto_20210621_1445'),
        ('task_management', '0017_alter_filesiswa_uploaded_at'),
    ]

    operations = [
    ]
