# Generated by Django 3.2.4 on 2021-06-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0018_merge_20210626_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesiswa',
            name='uploaded_at',
            field=models.DateTimeField(),
        ),
    ]
